module.exports = {  
  "CountryCode":{  
    "CurrencyCode":"Code",
    "CountryName":"Country"
  },
  "NZ":{  
    "CurrencyCode":"NZD",
    "CountryName":"New Zealand"
  },
  "CK":{  
    "CurrencyCode":"NZD",
    "CountryName":"Cook Islands"
  },
  "NU":{  
    "CurrencyCode":"NZD",
    "CountryName":"Niue"
  },
  "PN":{  
    "CurrencyCode":"NZD",
    "CountryName":"Pitcairn"
  },
  "TK":{  
    "CurrencyCode":"NZD",
    "CountryName":"Tokelau"
  },
  "AU":{  
    "CurrencyCode":"AUD",
    "CountryName":"Australian"
  },
  "CX":{  
    "CurrencyCode":"AUD",
    "CountryName":"Christmas Island"
  },
  "CC":{  
    "CurrencyCode":"AUD",
    "CountryName":"Cocos (Keeling) Islands"
  },
  "HM":{  
    "CurrencyCode":"AUD",
    "CountryName":"Heard and Mc Donald Islands"
  },
  "KI":{  
    "CurrencyCode":"AUD",
    "CountryName":"Kiribati"
  },
  "NR":{  
    "CurrencyCode":"AUD",
    "CountryName":"Nauru"
  },
  "NF":{  
    "CurrencyCode":"AUD",
    "CountryName":"Norfolk Island"
  },
  "TV":{  
    "CurrencyCode":"AUD",
    "CountryName":"Tuvalu"
  },
  "AS":{  
    "CurrencyCode":"EUR",
    "CountryName":"American Samoa"
  },
  "AD":{  
    "CurrencyCode":"EUR",
    "CountryName":"Andorra"
  },
  "AT":{  
    "CurrencyCode":"EUR",
    "CountryName":"Austria"
  },
  "BE":{  
    "CurrencyCode":"EUR",
    "CountryName":"Belgium"
  },
  "FI":{  
    "CurrencyCode":"EUR",
    "CountryName":"Finland"
  },
  "FR":{  
    "CurrencyCode":"EUR",
    "CountryName":"France"
  },
  "GF":{  
    "CurrencyCode":"EUR",
    "CountryName":"French Guiana"
  },
  "TF":{  
    "CurrencyCode":"EUR",
    "CountryName":"French Southern Territories"
  },
  "DE":{  
    "CurrencyCode":"EUR",
    "CountryName":"Germany"
  },
  "GR":{  
    "CurrencyCode":"EUR",
    "CountryName":"Greece"
  },
  "GP":{  
    "CurrencyCode":"EUR",
    "CountryName":"Guadeloupe"
  },
  "IE":{  
    "CurrencyCode":"EUR",
    "CountryName":"Ireland"
  },
  "IT":{  
    "CurrencyCode":"EUR",
    "CountryName":"Italy"
  },
  "LU":{  
    "CurrencyCode":"EUR",
    "CountryName":"Luxembourg"
  },
  "MQ":{  
    "CurrencyCode":"EUR",
    "CountryName":"Martinique"
  },
  "YT":{  
    "CurrencyCode":"EUR",
    "CountryName":"Mayotte"
  },
  "MC":{  
    "CurrencyCode":"EUR",
    "CountryName":"Monaco"
  },
  "NL":{  
    "CurrencyCode":"EUR",
    "CountryName":"Netherlands"
  },
  "PT":{  
    "CurrencyCode":"EUR",
    "CountryName":"Portugal"
  },
  "RE":{  
    "CurrencyCode":"EUR",
    "CountryName":"Reunion"
  },
  "WS":{  
    "CurrencyCode":"EUR",
    "CountryName":"Samoa"
  },
  "SM":{  
    "CurrencyCode":"EUR",
    "CountryName":"San Marino"
  },
  "SI":{  
    "CurrencyCode":"EUR",
    "CountryName":"Slovenia"
  },
  "ES":{  
    "CurrencyCode":"EUR",
    "CountryName":"Spain"
  },
  "VA":{  
    "CurrencyCode":"EUR",
    "CountryName":"Vatican City State (Holy See)"
  },
  "GS":{  
    "CurrencyCode":"GBP",
    "CountryName":"South Georgia and the South Sandwich Islands"
  },
  "GB":{  
    "CurrencyCode":"GBP",
    "CountryName":"United Kingdom"
  },
  "JE":{  
    "CurrencyCode":"GBP",
    "CountryName":"Jersey"
  },
  "IO":{  
    "CurrencyCode":"USD",
    "CountryName":"British Indian Ocean Territory"
  },
  "GU":{  
    "CurrencyCode":"USD",
    "CountryName":"Guam"
  },
  "MH":{  
    "CurrencyCode":"USD",
    "CountryName":"Marshall Islands"
  },
  "FM":{  
    "CurrencyCode":"USD",
    "CountryName":"Micronesia Federated States of"
  },
  "MP":{  
    "CurrencyCode":"USD",
    "CountryName":"Northern Mariana Islands"
  },
  "PW":{  
    "CurrencyCode":"USD",
    "CountryName":"Palau"
  },
  "PR":{  
    "CurrencyCode":"USD",
    "CountryName":"Puerto Rico"
  },
  "TC":{  
    "CurrencyCode":"USD",
    "CountryName":"Turks and Caicos Islands"
  },
  "US":{  
    "CurrencyCode":"USD",
    "CountryName":"United States"
  },
  "UM":{  
    "CurrencyCode":"USD",
    "CountryName":"United States Minor Outlying Islands"
  },
  "VG":{  
    "CurrencyCode":"USD",
    "CountryName":"Virgin Islands (British)"
  },
  "VI":{  
    "CurrencyCode":"USD",
    "CountryName":"Virgin Islands (US)"
  },
  "HK":{  
    "CurrencyCode":"HKD",
    "CountryName":"Hong Kong"
  },
  "CA":{  
    "CurrencyCode":"CAD",
    "CountryName":"Canada"
  },
  "JP":{  
    "CurrencyCode":"JPY",
    "CountryName":"Japan"
  },
  "AF":{  
    "CurrencyCode":"AFN",
    "CountryName":"Afghanistan"
  },
  "AL":{  
    "CurrencyCode":"ALL",
    "CountryName":"Albania"
  },
  "DZ":{  
    "CurrencyCode":"DZD",
    "CountryName":"Algeria"
  },
  "AI":{  
    "CurrencyCode":"XCD",
    "CountryName":"Anguilla"
  },
  "AG":{  
    "CurrencyCode":"XCD",
    "CountryName":"Antigua and Barbuda"
  },
  "DM":{  
    "CurrencyCode":"XCD",
    "CountryName":"Dominica"
  },
  "GD":{  
    "CurrencyCode":"XCD",
    "CountryName":"Grenada"
  },
  "MS":{  
    "CurrencyCode":"XCD",
    "CountryName":"Montserrat"
  },
  "KN":{  
    "CurrencyCode":"XCD",
    "CountryName":"Saint Kitts"
  },
  "LC":{  
    "CurrencyCode":"XCD",
    "CountryName":"Saint Lucia"
  },
  "VC":{  
    "CurrencyCode":"XCD",
    "CountryName":"Saint Vincent Grenadines"
  },
  "AR":{  
    "CurrencyCode":"ARS",
    "CountryName":"Argentina"
  },
  "AM":{  
    "CurrencyCode":"AMD",
    "CountryName":"Armenia"
  },
  "AW":{  
    "CurrencyCode":"ANG",
    "CountryName":"Aruba"
  },
  "AN":{  
    "CurrencyCode":"ANG",
    "CountryName":"Netherlands Antilles"
  },
  "AZ":{  
    "CurrencyCode":"AZN",
    "CountryName":"Azerbaijan"
  },
  "BS":{  
    "CurrencyCode":"BSD",
    "CountryName":"Bahamas"
  },
  "BH":{  
    "CurrencyCode":"BHD",
    "CountryName":"Bahrain"
  },
  "BD":{  
    "CurrencyCode":"BDT",
    "CountryName":"Bangladesh"
  },
  "BB":{  
    "CurrencyCode":"BBD",
    "CountryName":"Barbados"
  },
  "BY":{  
    "CurrencyCode":"BYR",
    "CountryName":"Belarus"
  },
  "BZ":{  
    "CurrencyCode":"BZD",
    "CountryName":"Belize"
  },
  "BJ":{  
    "CurrencyCode":"XOF",
    "CountryName":"Benin"
  },
  "BF":{  
    "CurrencyCode":"XOF",
    "CountryName":"Burkina Faso"
  },
  "GW":{  
    "CurrencyCode":"XOF",
    "CountryName":"Guinea-Bissau"
  },
  "CI":{  
    "CurrencyCode":"XOF",
    "CountryName":"Ivory Coast"
  },
  "ML":{  
    "CurrencyCode":"XOF",
    "CountryName":"Mali"
  },
  "NE":{  
    "CurrencyCode":"XOF",
    "CountryName":"Niger"
  },
  "SN":{  
    "CurrencyCode":"XOF",
    "CountryName":"Senegal"
  },
  "TG":{  
    "CurrencyCode":"XOF",
    "CountryName":"Togo"
  },
  "BM":{  
    "CurrencyCode":"BMD",
    "CountryName":"Bermuda"
  },
  "BT":{  
    "CurrencyCode":"INR",
    "CountryName":"Bhutan"
  },
  "IN":{  
    "CurrencyCode":"INR",
    "CountryName":"India"
  },
  "BO":{  
    "CurrencyCode":"BOB",
    "CountryName":"Bolivia"
  },
  "BW":{  
    "CurrencyCode":"BWP",
    "CountryName":"Botswana"
  },
  "BV":{  
    "CurrencyCode":"NOK",
    "CountryName":"Bouvet Island"
  },
  "NO":{  
    "CurrencyCode":"NOK",
    "CountryName":"Norway"
  },
  "SJ":{  
    "CurrencyCode":"NOK",
    "CountryName":"Svalbard and Jan Mayen Islands"
  },
  "BR":{  
    "CurrencyCode":"BRL",
    "CountryName":"Brazil"
  },
  "BN":{  
    "CurrencyCode":"BND",
    "CountryName":"Brunei Darussalam"
  },
  "BG":{  
    "CurrencyCode":"BGN",
    "CountryName":"Bulgaria"
  },
  "BI":{  
    "CurrencyCode":"BIF",
    "CountryName":"Burundi"
  },
  "KH":{  
    "CurrencyCode":"KHR",
    "CountryName":"Cambodia"
  },
  "CM":{  
    "CurrencyCode":"XAF",
    "CountryName":"Cameroon"
  },
  "CF":{  
    "CurrencyCode":"XAF",
    "CountryName":"Central African Republic"
  },
  "TD":{  
    "CurrencyCode":"XAF",
    "CountryName":"Chad"
  },
  "CG":{  
    "CurrencyCode":"XAF",
    "CountryName":"Congo Republic of the Democratic"
  },
  "GQ":{  
    "CurrencyCode":"XAF",
    "CountryName":"Equatorial Guinea"
  },
  "GA":{  
    "CurrencyCode":"XAF",
    "CountryName":"Gabon"
  },
  "CV":{  
    "CurrencyCode":"CVE",
    "CountryName":"Cape Verde"
  },
  "KY":{  
    "CurrencyCode":"KYD",
    "CountryName":"Cayman Islands"
  },
  "CL":{  
    "CurrencyCode":"CLP",
    "CountryName":"Chile"
  },
  "CN":{  
    "CurrencyCode":"CNY",
    "CountryName":"China"
  },
  "CO":{  
    "CurrencyCode":"COP",
    "CountryName":"Colombia"
  },
  "KM":{  
    "CurrencyCode":"KMF",
    "CountryName":"Comoros"
  },
  "CD":{  
    "CurrencyCode":"CDF",
    "CountryName":"Congo (Kinshasa)"
  },
  "CR":{  
    "CurrencyCode":"CRC",
    "CountryName":"Costa Rica"
  },
  "HR":{  
    "CurrencyCode":"HRK",
    "CountryName":"Croatia (Hrvatska)"
  },
  "CU":{  
    "CurrencyCode":"CUP",
    "CountryName":"Cuba"
  },
  "CY":{  
    "CurrencyCode":"CYP",
    "CountryName":"Cyprus"
  },
  "CZ":{  
    "CurrencyCode":"CZK",
    "CountryName":"Czech Republic"
  },
  "DK":{  
    "CurrencyCode":"DKK",
    "CountryName":"Denmark"
  },
  "FO":{  
    "CurrencyCode":"DKK",
    "CountryName":"Faroe Islands"
  },
  "GL":{  
    "CurrencyCode":"DKK",
    "CountryName":"Greenland"
  },
  "DJ":{  
    "CurrencyCode":"DJF",
    "CountryName":"Djibouti"
  },
  "DO":{  
    "CurrencyCode":"DOP",
    "CountryName":"Dominican Republic"
  },
  "TP":{  
    "CurrencyCode":"IDR",
    "CountryName":"East Timor"
  },
  "ID":{  
    "CurrencyCode":"IDR",
    "CountryName":"Indonesia"
  },
  "EC":{  
    "CurrencyCode":"ECS",
    "CountryName":"Ecuador"
  },
  "EG":{  
    "CurrencyCode":"EGP",
    "CountryName":"Egypt"
  },
  "SV":{  
    "CurrencyCode":"SVC",
    "CountryName":"El Salvador"
  },
  "ER":{  
    "CurrencyCode":"ETB",
    "CountryName":"Eritrea"
  },
  "ET":{  
    "CurrencyCode":"ETB",
    "CountryName":"Ethiopia"
  },
  "EE":{  
    "CurrencyCode":"EEK",
    "CountryName":"Estonia"
  },
  "FK":{  
    "CurrencyCode":"FKP",
    "CountryName":"Falkland Islands (Malvinas)"
  },
  "FJ":{  
    "CurrencyCode":"FJD",
    "CountryName":"Fiji"
  },
  "PF":{  
    "CurrencyCode":"XPF",
    "CountryName":"French Polynesia"
  },
  "NC":{  
    "CurrencyCode":"XPF",
    "CountryName":"New Caledonia"
  },
  "WF":{  
    "CurrencyCode":"XPF",
    "CountryName":"Wallis and Futuna Islands"
  },
  "GM":{  
    "CurrencyCode":"GMD",
    "CountryName":"Gambia"
  },
  "GE":{  
    "CurrencyCode":"GEL",
    "CountryName":"Georgia"
  },
  "GI":{  
    "CurrencyCode":"GIP",
    "CountryName":"Gibraltar"
  },
  "GT":{  
    "CurrencyCode":"GTQ",
    "CountryName":"Guatemala"
  },
  "GN":{  
    "CurrencyCode":"GNF",
    "CountryName":"Guinea"
  },
  "GY":{  
    "CurrencyCode":"GYD",
    "CountryName":"Guyana"
  },
  "HT":{  
    "CurrencyCode":"HTG",
    "CountryName":"Haiti"
  },
  "HN":{  
    "CurrencyCode":"HNL",
    "CountryName":"Honduras"
  },
  "HU":{  
    "CurrencyCode":"HUF",
    "CountryName":"Hungary"
  },
  "IS":{  
    "CurrencyCode":"ISK",
    "CountryName":"Iceland"
  },
  "IR":{  
    "CurrencyCode":"IRR",
    "CountryName":"Iran (Islamic Republic of)"
  },
  "IQ":{  
    "CurrencyCode":"IQD",
    "CountryName":"Iraq"
  },
  "IL":{  
    "CurrencyCode":"ILS",
    "CountryName":"Israel"
  },
  "JM":{  
    "CurrencyCode":"JMD",
    "CountryName":"Jamaica"
  },
  "JO":{  
    "CurrencyCode":"JOD",
    "CountryName":"Jordan"
  },
  "KZ":{  
    "CurrencyCode":"KZT",
    "CountryName":"Kazakhstan"
  },
  "KE":{  
    "CurrencyCode":"KES",
    "CountryName":"Kenya"
  },
  "KP":{  
    "CurrencyCode":"KPW",
    "CountryName":"Korea North"
  },
  "KR":{  
    "CurrencyCode":"KRW",
    "CountryName":"Korea South"
  },
  "KW":{  
    "CurrencyCode":"KWD",
    "CountryName":"Kuwait"
  },
  "KG":{  
    "CurrencyCode":"KGS",
    "CountryName":"Kyrgyzstan"
  },
  "LA":{  
    "CurrencyCode":"LAK",
    "CountryName":"Laos"
  },
  "LV":{  
    "CurrencyCode":"LVL",
    "CountryName":"Latvia"
  },
  "LB":{  
    "CurrencyCode":"LBP",
    "CountryName":"Lebanon"
  },
  "LS":{  
    "CurrencyCode":"LSL",
    "CountryName":"Lesotho"
  },
  "LR":{  
    "CurrencyCode":"LRD",
    "CountryName":"Liberia"
  },
  "LY":{  
    "CurrencyCode":"LYD",
    "CountryName":"Libyan Arab Jamahiriya"
  },
  "LI":{  
    "CurrencyCode":"CHF",
    "CountryName":"Liechtenstein"
  },
  "CH":{  
    "CurrencyCode":"CHF",
    "CountryName":"Switzerland"
  },
  "LT":{  
    "CurrencyCode":"LTL",
    "CountryName":"Lithuania"
  },
  "MO":{  
    "CurrencyCode":"MOP",
    "CountryName":"Macao S.A.R."
  },
  "MK":{  
    "CurrencyCode":"MKD",
    "CountryName":"Macedonia"
  },
  "MG":{  
    "CurrencyCode":"MGA",
    "CountryName":"Madagascar"
  },
  "MW":{  
    "CurrencyCode":"MWK",
    "CountryName":"Malawi"
  },
  "MY":{  
    "CurrencyCode":"MYR",
    "CountryName":"Malaysia"
  },
  "MV":{  
    "CurrencyCode":"MVR",
    "CountryName":"Maldives"
  },
  "MT":{  
    "CurrencyCode":"MTL",
    "CountryName":"Malta"
  },
  "MR":{  
    "CurrencyCode":"MRO",
    "CountryName":"Mauritania"
  },
  "MU":{  
    "CurrencyCode":"MUR",
    "CountryName":"Mauritius"
  },
  "MX":{  
    "CurrencyCode":"MXN",
    "CountryName":"Mexico"
  },
  "MD":{  
    "CurrencyCode":"MDL",
    "CountryName":"Moldova Republic of"
  },
  "MN":{  
    "CurrencyCode":"MNT",
    "CountryName":"Mongolia"
  },
  "MA":{  
    "CurrencyCode":"MAD",
    "CountryName":"Morocco"
  },
  "EH":{  
    "CurrencyCode":"MAD",
    "CountryName":"Western Sahara"
  },
  "MZ":{  
    "CurrencyCode":"MZN",
    "CountryName":"Mozambique"
  },
  "MM":{  
    "CurrencyCode":"MMK",
    "CountryName":"Myanmar"
  },
  "NA":{  
    "CurrencyCode":"NAD",
    "CountryName":"Namibia"
  },
  "NP":{  
    "CurrencyCode":"NPR",
    "CountryName":"Nepal"
  },
  "NI":{  
    "CurrencyCode":"NIO",
    "CountryName":"Nicaragua"
  },
  "NG":{  
    "CurrencyCode":"NGN",
    "CountryName":"Nigeria"
  },
  "OM":{  
    "CurrencyCode":"OMR",
    "CountryName":"Oman"
  },
  "PK":{  
    "CurrencyCode":"PKR",
    "CountryName":"Pakistan"
  },
  "PA":{  
    "CurrencyCode":"PAB",
    "CountryName":"Panama"
  },
  "PG":{  
    "CurrencyCode":"PGK",
    "CountryName":"Papua New Guinea"
  },
  "PY":{  
    "CurrencyCode":"PYG",
    "CountryName":"Paraguay"
  },
  "PE":{  
    "CurrencyCode":"PEN",
    "CountryName":"Peru"
  },
  "PH":{  
    "CurrencyCode":"PHP",
    "CountryName":"Philippines"
  },
  "PL":{  
    "CurrencyCode":"PLN",
    "CountryName":"Poland"
  },
  "QA":{  
    "CurrencyCode":"QAR",
    "CountryName":"Qatar"
  },
  "RO":{  
    "CurrencyCode":"RON",
    "CountryName":"Romania"
  },
  "RU":{  
    "CurrencyCode":"RUB",
    "CountryName":"Russian Federation"
  },
  "RW":{  
    "CurrencyCode":"RWF",
    "CountryName":"Rwanda"
  },
  "ST":{  
    "CurrencyCode":"STD",
    "CountryName":"Sao Tome and Principe"
  },
  "SA":{  
    "CurrencyCode":"SAR",
    "CountryName":"Saudi Arabia"
  },
  "SC":{  
    "CurrencyCode":"SCR",
    "CountryName":"Seychelles"
  },
  "SL":{  
    "CurrencyCode":"SLL",
    "CountryName":"Sierra Leone"
  },
  "SG":{  
    "CurrencyCode":"SGD",
    "CountryName":"Singapore"
  },
  "SK":{  
    "CurrencyCode":"SKK",
    "CountryName":"Slovakia (Slovak Republic)"
  },
  "SB":{  
    "CurrencyCode":"SBD",
    "CountryName":"Solomon Islands"
  },
  "SO":{  
    "CurrencyCode":"SOS",
    "CountryName":"Somalia"
  },
  "ZA":{  
    "CurrencyCode":"ZAR",
    "CountryName":"South Africa"
  },
  "LK":{  
    "CurrencyCode":"LKR",
    "CountryName":"Sri Lanka"
  },
  "SD":{  
    "CurrencyCode":"SDG",
    "CountryName":"Sudan"
  },
  "SR":{  
    "CurrencyCode":"SRD",
    "CountryName":"Suriname"
  },
  "SZ":{  
    "CurrencyCode":"SZL",
    "CountryName":"Swaziland"
  },
  "SE":{  
    "CurrencyCode":"SEK",
    "CountryName":"Sweden"
  },
  "SY":{  
    "CurrencyCode":"SYP",
    "CountryName":"Syrian Arab Republic"
  },
  "TW":{  
    "CurrencyCode":"TWD",
    "CountryName":"Taiwan"
  },
  "TJ":{  
    "CurrencyCode":"TJS",
    "CountryName":"Tajikistan"
  },
  "TZ":{  
    "CurrencyCode":"TZS",
    "CountryName":"Tanzania"
  },
  "TH":{  
    "CurrencyCode":"THB",
    "CountryName":"Thailand"
  },
  "TO":{  
    "CurrencyCode":"TOP",
    "CountryName":"Tonga"
  },
  "TT":{  
    "CurrencyCode":"TTD",
    "CountryName":"Trinidad and Tobago"
  },
  "TN":{  
    "CurrencyCode":"TND",
    "CountryName":"Tunisia"
  },
  "TR":{  
    "CurrencyCode":"TRY",
    "CountryName":"Turkey"
  },
  "TM":{  
    "CurrencyCode":"TMT",
    "CountryName":"Turkmenistan"
  },
  "UG":{  
    "CurrencyCode":"UGX",
    "CountryName":"Uganda"
  },
  "UA":{  
    "CurrencyCode":"UAH",
    "CountryName":"Ukraine"
  },
  "AE":{  
    "CurrencyCode":"AED",
    "CountryName":"United Arab Emirates"
  },
  "UY":{  
    "CurrencyCode":"UYU",
    "CountryName":"Uruguay"
  },
  "UZ":{  
    "CurrencyCode":"UZS",
    "CountryName":"Uzbekistan"
  },
  "VU":{  
    "CurrencyCode":"VUV",
    "CountryName":"Vanuatu"
  },
  "VE":{  
    "CurrencyCode":"VEF",
    "CountryName":"Venezuela"
  },
  "VN":{  
    "CurrencyCode":"VND",
    "CountryName":"Vietnam"
  },
  "YE":{  
    "CurrencyCode":"YER",
    "CountryName":"Yemen"
  },
  "ZM":{  
    "CurrencyCode":"ZMK",
    "CountryName":"Zambia"
  },
  "ZW":{  
    "CurrencyCode":"ZWD",
    "CountryName":"Zimbabwe"
  },
  "AX":{  
    "CurrencyCode":"EUR",
    "CountryName":"Aland Islands"
  },
  "AO":{  
    "CurrencyCode":"AOA",
    "CountryName":"Angola"
  },
  "AQ":{  
    "CurrencyCode":"AQD",
    "CountryName":"Antarctica"
  },
  "BA":{  
    "CurrencyCode":"BAM",
    "CountryName":"Bosnia and Herzegovina"
  },
  "GH":{  
    "CurrencyCode":"GHS",
    "CountryName":"Ghana"
  },
  "GG":{  
    "CurrencyCode":"GGP",
    "CountryName":"Guernsey"
  },
  "IM":{  
    "CurrencyCode":"GBP",
    "CountryName":"Isle of Man"
  },
  "ME":{  
    "CurrencyCode":"EUR",
    "CountryName":"Montenegro"
  },
  "PS":{  
    "CurrencyCode":"JOD",
    "CountryName":"Palestinian Territory"
  },
  "BL":{  
    "CurrencyCode":"EUR",
    "CountryName":"Saint Barthelemy"
  },
  "SH":{  
    "CurrencyCode":"GBP",
    "CountryName":"Saint Helena"
  },
  "MF":{  
    "CurrencyCode":"ANG",
    "CountryName":"Saint Martin (French part)"
  },
  "PM":{  
    "CurrencyCode":"EUR",
    "CountryName":"Saint Pierre and Miquelon"
  },
  "RS":{  
    "CurrencyCode":"RSD",
    "CountryName":"Serbia"
  },
  "USAF":{  
    "CurrencyCode":"USD",
    "CountryName":"US Armed Forces"
  }
}